1. Creating arrays

In [3]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2. Array operations

In [5]:
a=np.array([10,20,30])
b=np.array([1,2,3])

print(a+b)
print(a*b)
print(a-b)
print(a/b)

[11 22 33]
[10 40 90]
[ 9 18 27]
[10. 10. 10.]


3. Zeros and Ones

In [6]:
print(np.zeros((2,3)))
print(np.ones((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4. Mean, Max, Min

In [7]:
data=np.array([10,20,30,40])

print("Mean: ", np.mean(data))
print("Max: ", np.max(data))
print("Min: ", np.min(data))

Mean:  25.0
Max:  40
Min:  10
